# Generated by Django 3.0.5 on 2020-04-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('dt', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
