# Generated by Django 3.0.5 on 2020-05-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piaui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('casos', models.IntegerField(verbose_name='Casos')),
                ('obitos', models.IntegerField(verbose_name='Óbitos')),
            ],
        ),
    ]
