# Generated by Django 3.0.5 on 2020-05-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_piaui'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasosPorCidadePiaui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idIBGE', models.IntegerField(verbose_name='IBGE ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('casos', models.IntegerField(verbose_name='Casos')),
                ('obitos', models.IntegerField(verbose_name='Óbitos')),
            ],
            options={
                'verbose_name': 'CasosPorCidadePiaui',
                'verbose_name_plural': 'CasosPorCidadePiauis',
            },
        ),
        migrations.DeleteModel(
            name='Piaui',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
