# Generated by Django 3.0.5 on 2020-05-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200506_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casosporcidadepiaui',
            name='id',
        ),
        migrations.AlterField(
            model_name='casosporcidadepiaui',
            name='idIBGE',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='IBGE ID'),
        ),
    ]
